// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0-v11C_bKeiLatK5Seoe-Wqv3jv2YeCs',
    appId: '1:705634457564:web:d364aa9a908e48627a2119',
    messagingSenderId: '705634457564',
    projectId: 'drink-water-tracker',
    authDomain: 'drink-water-tracker.firebaseapp.com',
    storageBucket: 'drink-water-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJNFxCw0TEu7WqFYsNwuOHgg0oSuqzFzU',
    appId: '1:705634457564:android:b6165d84ad2d3fd37a2119',
    messagingSenderId: '705634457564',
    projectId: 'drink-water-tracker',
    storageBucket: 'drink-water-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsEia0ck9sl-2qPtFf_aqf2cAUZsaZwao',
    appId: '1:705634457564:ios:6709a4a13df1c48e7a2119',
    messagingSenderId: '705634457564',
    projectId: 'drink-water-tracker',
    storageBucket: 'drink-water-tracker.appspot.com',
    iosClientId: '705634457564-de9krc9vcje007hrirp7hjki00d08sr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsEia0ck9sl-2qPtFf_aqf2cAUZsaZwao',
    appId: '1:705634457564:ios:6709a4a13df1c48e7a2119',
    messagingSenderId: '705634457564',
    projectId: 'drink-water-tracker',
    storageBucket: 'drink-water-tracker.appspot.com',
    iosClientId: '705634457564-de9krc9vcje007hrirp7hjki00d08sr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterTracker',
  );
}
